import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import { Button } from '~/components/Button';
import { ModalA } from '~/components/Modals/ModalA';
import { ModalB } from '~/components/Modals/ModalB';
import { Typography } from '~/components/Typography';
import { useCustomModal } from '~/hooks/useModal';

const Main = styled.main`
  background-color: ${(props) => props.theme.colors.customGray00};
  color: ${(props) => props.theme.colors.brandBlue};
  display: grid;
  place-items: center;
  height: 100vh;
  width: 100%;
`;

const Home: NextPage = () => {
  const [openModalA] = useCustomModal(ModalA);
  const [openModalB] = useCustomModal(ModalB);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Typography as="h1" variant="heading1">
          useModal
        </Typography>

        <Typography as="p" variant="body">
          Home Page
        </Typography>

        <Button variant="contained-secondary-md" onClick={openModalA}>
          Open Modal A
        </Button>

        <Button variant="contained-secondary-md" onClick={() => openModalB({ title: 'Modal B Baby' })}>
          Open Modal B
        </Button>
      </Main>
    </>
  );
};

export default Home;
